name: Build Main

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [1.18.x]

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint
        run: deno fmt --check

      - name: Build
        run: deno run --reload index.ts

      - name: Tests
        run: deno test --allow-net
